# Generated by Django 2.2.12 on 2022-09-10 15:55

import django.contrib.postgres.fields.ranges
from django.db import migrations, models

import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PropostaEditalFomento",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("periodo_inscricao", django.contrib.postgres.fields.ranges.DateRangeField()),
                ("periodo_selecao", django.contrib.postgres.fields.ranges.DateRangeField()),
                ("estado", django_fsm.FSMIntegerField(default=1, protected=True)),
                ("aberta_em", models.DateTimeField(auto_now_add=True)),
                ("atualizada_em", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
